[amplifier_component]
# pem format cert
identity = '''
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
'''
url = "https://amplifier-devnet-amplifier.devnet.axelar.dev/"
chain = "solana-devnet"

[relayer_engine]
[relayer_engine.health_check]
bind_addr = "0.0.0.0:3000"

[solana_listener_component]
solana_http_rpc = "https://api.devnet.solana.com"

# the officia ws endpoints hosted by solana sometimes refuse to accept new connections / drop the connection frequently.
# using helius hosted nodes (even the free tier) often at times yields better results.
solana_ws = "wss://api.devnet.solana.com"
# solana_ws = "wss://devnet.helius-rpc.com/?{your api key}"
missed_signature_catchup_strategy = "until_beginning"
