permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: check
jobs:
  fmt:
    runs-on: self-hosted
    name: check
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      - name: cargo xtask check
        run: cargo xtask check
